services:
  docs:
    image: crypto_town_local_docs
    container_name: crypto_town_local_docs
    build:
      context: .
      dockerfile: ./compose/local/docs/Dockerfile
    env_file:
      - ./.envs/.local/.django
    volumes:
      - /app/.venv
      - ./docs:/docs:z
      - ./config:/app/config:z
      - ./crypto_town:/app/crypto_town:z
    ports:
      - '9000:9000'
    command: /start-docs
